[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
clap = { version ="4.5.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
